import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore') # Hides annoying sci-kit warnings

print("EV Traction Motor Thermal Predictive Engine Active\n")

# 1. Load Data generated by the Digital Twin
try:
    print("Loading synthetic physics data from the Digital Twin...")
    powertrain_telemetry = pd.read_csv('synthetic_motor_data.csv')
    print("Data loaded successfully! Training AI brain...\n")
except FileNotFoundError:
    print("ERROR: I can't find 'synthetic_motor_data.csv'!")
    exit()

# 2. Split Data Channels into Inputs (X) and Target (y)
X = powertrain_telemetry[['Stator_Current_Amps', 'Coolant_Flow_Lmin']]
y = powertrain_telemetry['Turtle_Trigger']

# We use a smaller test_size here since our twin only generated 10 rows!
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

# 3. Train the Predictive VCU Brain
ai_brain = LogisticRegression()
ai_brain.fit(X_train, y_train)

# Validate performance
predictions = ai_brain.predict(X_test)
score = accuracy_score(y_test, predictions)

print(f"VCU Core Training complete. Algorithm Prediction Accuracy: {score * 100:.1f}%\n")
print("-" * 65)
print("LIVE COCKPIT DIAGNOSTIC INTERFACE (EMULATING VEHICLE CAN BUS):")
print("-" * 65)

# 4. Interactive Live Prediction Interface
try:
    user_amps = float(input("Enter Live Inverter Stator Current (e.g. 400): "))
    user_flow = float(input("Enter Live Cooling Flow Rate (e.g. 3.0): "))
    
    sensor_packet = pd.DataFrame([[user_amps, user_flow]], columns=['Stator_Current_Amps', 'Coolant_Flow_Lmin'])
    prediction = ai_brain.predict(sensor_packet)[0]
    
    print("\n" + "="*55)
    print("EV POWERTRAIN SYSTEM STATUS REPORT:")
    print("="*55)
    if prediction == 1:
        print("ALERT: CRITICAL STATOR THERMAL OVERLOAD DETECTED!")
        print("Action: Engaging [TURTLE MODE]")
    else:
        print("STATUS: [SMOOTH CRUISE]")
        print("Thermal management optimal. Continuous torque permitted.")
    print("="*55)

except ValueError:
    print("Error: Input mismatch. Please enter numerical values only.")
